# Generated by Django 4.1 on 2023-05-13 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users1',
            field=models.ManyToManyField(related_name='users1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users2',
            field=models.ManyToManyField(related_name='users2', to=settings.AUTH_USER_MODEL),
        ),
    ]
