# Generated by Django 4.1 on 2023-05-13 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0004_remove_chatroom_users_chatroom_users1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='users2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
